[workspace]
resolver = "2"
members = ["crates/limn", "crates/rantlr-lex", "crates/rantlr-grammar", "crates/rantlr-engine", "crates/rantlr-services", "crates/rantlr-lsp", "crates/rantlr-sem", "crates/rantlr-rg", "crates/rantlr-cli"]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
