// @generated by qana (qana2ts). DO NOT EDIT.
// Emitted from the envelope-certified `Demo` grammar: deterministic
// LR(1), so tree-sitter's GLR power is never needed — precedence
// annotations below carry the same declarative disambiguation.
// NOTE: mode `BLOCK` emitted as recursive extra `block_comment`: tree-sitter nests it unboundedly where the envelope caps depth at 8 — permissive-direction divergence
// NOTE: error-flavored token `STRING_UNTERM` skipped (tree-sitter's own ERROR recovery covers it)
module.exports = grammar({
  name: 'demo',
  word: $ => $.ident,
  extras: $ => [/\s/, $.block_comment, $.line_comment],
  rules: {
    file: $ => optional($.stmts),
    stmts: $ => repeat1($.stmt),
    stmt: $ => choice(seq('let', field("name", $.ident), '=', $.expr, ';'), seq($.expr, ';'), $.block, seq('if', '(', $.expr, ')', $.block), seq('if', '(', $.expr, ')', $.block, 'else', $.block)),
    block: $ => seq('{', optional($.stmts), '}'),
    expr: $ => choice(prec.left(1, seq($.expr, '+', $.expr)), prec.left(1, seq($.expr, '-', $.expr)), prec.left(2, seq($.expr, '*', $.expr)), prec.left(2, seq($.expr, '/', $.expr)), $.number, $.string, $.ident, seq($.ident, '(', optional($.args), ')'), seq('(', $.expr, ')'), seq('[', optional($.args), ']')),
    args: $ => $.args_ne,
    args_ne: $ => seq($.expr, repeat(seq(',', $.expr))),
    string: $ => /"(?:\\[^\r\n]|[^"\\\r\n])*"/,
    number: $ => /[0-9]+(?:\.[0-9]+)?/,
    ident: $ => /[_\p{L}][_\p{L}\p{N}]*/,
    punct: $ => /[!-\/:-@[-`{-~]/,
    block_comment: $ => seq('/*', repeat(choice($.block_comment, /[^*\/\r\n]+/, /[*\/]/)), '*/'),
    line_comment: $ => /\/\/[^\r\n]*/,
  }
});
