// @generated by qana (qana2ts). DO NOT EDIT.
// Emitted from the envelope-certified `Qana` grammar: deterministic
// LR(1), so tree-sitter's GLR power is never needed — precedence
// annotations below carry the same declarative disambiguation.
// NOTE: error-flavored token `STRING_UNTERM` skipped (tree-sitter's own ERROR recovery covers it)
// NOTE: error-flavored token `PATTERN_UNTERM` skipped (tree-sitter's own ERROR recovery covers it)
module.exports = grammar({
  name: 'qana',
  word: $ => $.name,
  extras: $ => [/\s/, $.line_comment],
  rules: {
    file: $ => optional($.decls),
    decls: $ => repeat1($.decl),
    decl: $ => choice(seq('language', $.name), seq('max_stack', $.num), seq('keywords', $.name, '=', $.kw_list), $.token_def, seq('mode', $.name, '{', optional($.token_defs), '}'), seq('pair', $.tok_ref, $.tok_ref), seq('prec', $.assoc, $.prec_ops), seq('start', $.name), seq('rule', field("name", $.name), '=', $.alt_list), seq('rule', field("name", $.name), '=', '|', $.alt_list), seq('rule', field("name", $.name), '=', $.elem, '*', optional($.rep_sep)), seq('rule', field("name", $.name), '=', $.elem, '+', optional($.rep_sep)), seq('rule', field("name", $.name), '=', $.elem, '?')),
    token_def: $ => seq('token', field("name", $.name), '=', $.tok_pat, optional($.attrs)),
    token_defs: $ => repeat1($.token_def),
    kw_list: $ => repeat1($.kw_item),
    kw_item: $ => choice($.name, $.string),
    tok_pat: $ => choice($.pattern, $.string),
    attrs: $ => repeat1($.attr),
    attr: $ => choice(seq('@', $.name), seq('@', $.name, '(', $.arg_list, ')')),
    arg_list: $ => seq($.arg, repeat(seq(',', $.arg))),
    arg: $ => choice($.name, $.num, $.string),
    tok_ref: $ => choice($.name, $.string),
    assoc: $ => choice('left', 'right'),
    prec_ops: $ => repeat1($.tok_ref),
    alt_list: $ => seq($.alt, repeat(seq('|', $.alt))),
    alt: $ => seq($.name, ':', optional($.syms), optional($.attrs)),
    syms: $ => repeat1($.sym),
    sym: $ => choice($.name, $.string, seq($.name, ':', $.name), seq($.name, ':', $.string), seq($.name, '?'), seq($.name, '*'), seq($.name, '+'), seq($.string, '?'), seq($.string, '*'), seq($.string, '+')),
    elem: $ => choice($.name, $.string),
    rep_sep: $ => seq('%', $.elem),
    name: $ => /[_\p{L}][_\p{L}\p{N}]*/,
    num: $ => /[0-9]+/,
    string: $ => /"(?:\\[^\r\n]|[^"\\\r\n])*"/,
    pattern: $ => /\/(?:\\[^\r\n]|[^\/\\\r\n])(?:\\[^\r\n]|[^\/\\\r\n])*\//,
    line_comment: $ => /\/\/[^\r\n]*/,
  }
});
