; @generated by qana (qana2ts). DO NOT EDIT.
; Derived from the grammar's @style annotations.
(line_comment) @comment
(block_comment) @comment
(string) @string
(number) @number
(ident) @variable
['(' ')' '[' ']' '{' '}'] @punctuation.bracket
['+' '-' '*' '/' '='] @operator
[';' ','] @punctuation.delimiter
(punct) @punctuation.delimiter
['fn' 'let' 'if' 'else' 'while' 'for' 'return' 'struct' 'enum' 'impl' 'match' 'true' 'false' 'mut' 'pub' 'use'] @keyword
