; @generated by rantlr (rg2ts). DO NOT EDIT.
; Derived from the grammar's @style annotations.
(line_comment) @comment
(name) @variable
(num) @number
(string) @string
(pattern) @string.regexp
['=' '|' '*' '+' '?' '%'] @operator
[':' '@' ','] @punctuation.delimiter
['(' ')' '{' '}'] @punctuation.bracket
['language' 'max_stack' 'keywords' 'token' 'mode' 'pair' 'prec' 'left' 'right' 'start' 'rule'] @keyword
