//! @generated by `cargo run -p rantlr-grammar --bin astgen`.
//! Typed AST for the `DemoSyn` grammar. DO NOT EDIT.
#![allow(dead_code)]

use crate::typed::{AstNode, NodeRef, TokenRef};

/// `file → stmts`
#[derive(Clone, Copy, Debug)]
pub struct File<'g>(pub NodeRef<'g>);

impl<'g> AstNode<'g> for File<'g> {
    fn cast(node: NodeRef<'g>) -> Option<Self> {
        (node.nt() == 0 && node.prod() == 0).then(|| File(node))
    }
    fn node(&self) -> NodeRef<'g> {
        self.0
    }
}

impl<'g> File<'g> {
    pub fn stmts(&self) -> Option<Stmts<'g>> {
        Stmts::cast(self.0.child_node(0)?)
    }
}

/// `stmts` — balanced list of `Stmt` (envelope L4).
#[derive(Clone, Copy, Debug)]
pub struct Stmts<'g>(pub NodeRef<'g>);

impl<'g> AstNode<'g> for Stmts<'g> {
    fn cast(node: NodeRef<'g>) -> Option<Self> {
        (node.nt() == 1 && node.prod() == crate::green::LIST_PROD).then(|| Stmts(node))
    }
    fn node(&self) -> NodeRef<'g> {
        self.0
    }
}

impl<'g> Stmts<'g> {
    pub fn items(&self) -> Vec<Stmt<'g>> {
        self.0
            .flat_symbol_children()
            .into_iter()
            .filter_map(|c| match c {
                crate::typed::SymbolChild::Node(n) => Stmt::cast(n),
                _ => None,
            })
            .collect()
    }
}

/// `stmt` — 5 productions.
#[derive(Clone, Copy, Debug)]
pub enum Stmt<'g> {
    LetStmt(LetStmt<'g>),
    ExprStmt(ExprStmt<'g>),
    BlockStmt(BlockStmt<'g>),
    IfStmt(IfStmt<'g>),
    IfElseStmt(IfElseStmt<'g>),
}

impl<'g> AstNode<'g> for Stmt<'g> {
    fn cast(node: NodeRef<'g>) -> Option<Self> {
        if node.nt() != 2 {
            return None;
        }
        match node.prod() {
            3 => Some(Stmt::LetStmt(LetStmt(node))),
            4 => Some(Stmt::ExprStmt(ExprStmt(node))),
            5 => Some(Stmt::BlockStmt(BlockStmt(node))),
            6 => Some(Stmt::IfStmt(IfStmt(node))),
            7 => Some(Stmt::IfElseStmt(IfElseStmt(node))),
            _ => None,
        }
    }
    fn node(&self) -> NodeRef<'g> {
        match self {
            Stmt::LetStmt(x) => x.0,
            Stmt::ExprStmt(x) => x.0,
            Stmt::BlockStmt(x) => x.0,
            Stmt::IfStmt(x) => x.0,
            Stmt::IfElseStmt(x) => x.0,
        }
    }
}

/// `stmt → KW_LET IDENT EQ expr SEMI`
#[derive(Clone, Copy, Debug)]
pub struct LetStmt<'g>(pub NodeRef<'g>);

impl<'g> AstNode<'g> for LetStmt<'g> {
    fn cast(node: NodeRef<'g>) -> Option<Self> {
        (node.nt() == 2 && node.prod() == 3).then(|| LetStmt(node))
    }
    fn node(&self) -> NodeRef<'g> {
        self.0
    }
}

impl<'g> LetStmt<'g> {
    pub fn kw_let_token(&self) -> Option<TokenRef<'g>> {
        self.0.child_token(0, 22) // KW_LET
    }
    pub fn ident_token(&self) -> Option<TokenRef<'g>> {
        self.0.child_token(1, 6) // IDENT
    }
    pub fn eq_token(&self) -> Option<TokenRef<'g>> {
        self.0.child_token(2, 19) // EQ
    }
    pub fn expr(&self) -> Option<Expr<'g>> {
        Expr::cast(self.0.child_node(3)?)
    }
    pub fn semi_token(&self) -> Option<TokenRef<'g>> {
        self.0.child_token(4, 17) // SEMI
    }
}

/// `stmt → expr SEMI`
#[derive(Clone, Copy, Debug)]
pub struct ExprStmt<'g>(pub NodeRef<'g>);

impl<'g> AstNode<'g> for ExprStmt<'g> {
    fn cast(node: NodeRef<'g>) -> Option<Self> {
        (node.nt() == 2 && node.prod() == 4).then(|| ExprStmt(node))
    }
    fn node(&self) -> NodeRef<'g> {
        self.0
    }
}

impl<'g> ExprStmt<'g> {
    pub fn expr(&self) -> Option<Expr<'g>> {
        Expr::cast(self.0.child_node(0)?)
    }
    pub fn semi_token(&self) -> Option<TokenRef<'g>> {
        self.0.child_token(1, 17) // SEMI
    }
}

/// `stmt → block`
#[derive(Clone, Copy, Debug)]
pub struct BlockStmt<'g>(pub NodeRef<'g>);

impl<'g> AstNode<'g> for BlockStmt<'g> {
    fn cast(node: NodeRef<'g>) -> Option<Self> {
        (node.nt() == 2 && node.prod() == 5).then(|| BlockStmt(node))
    }
    fn node(&self) -> NodeRef<'g> {
        self.0
    }
}

impl<'g> BlockStmt<'g> {
    pub fn block(&self) -> Option<Block<'g>> {
        Block::cast(self.0.child_node(0)?)
    }
}

/// `stmt → KW_IF LPAREN expr RPAREN block`
#[derive(Clone, Copy, Debug)]
pub struct IfStmt<'g>(pub NodeRef<'g>);

impl<'g> AstNode<'g> for IfStmt<'g> {
    fn cast(node: NodeRef<'g>) -> Option<Self> {
        (node.nt() == 2 && node.prod() == 6).then(|| IfStmt(node))
    }
    fn node(&self) -> NodeRef<'g> {
        self.0
    }
}

impl<'g> IfStmt<'g> {
    pub fn kw_if_token(&self) -> Option<TokenRef<'g>> {
        self.0.child_token(0, 23) // KW_IF
    }
    pub fn lparen_token(&self) -> Option<TokenRef<'g>> {
        self.0.child_token(1, 7) // LPAREN
    }
    pub fn expr(&self) -> Option<Expr<'g>> {
        Expr::cast(self.0.child_node(2)?)
    }
    pub fn rparen_token(&self) -> Option<TokenRef<'g>> {
        self.0.child_token(3, 8) // RPAREN
    }
    pub fn block(&self) -> Option<Block<'g>> {
        Block::cast(self.0.child_node(4)?)
    }
}

/// `stmt → KW_IF LPAREN expr RPAREN block KW_ELSE block`
#[derive(Clone, Copy, Debug)]
pub struct IfElseStmt<'g>(pub NodeRef<'g>);

impl<'g> AstNode<'g> for IfElseStmt<'g> {
    fn cast(node: NodeRef<'g>) -> Option<Self> {
        (node.nt() == 2 && node.prod() == 7).then(|| IfElseStmt(node))
    }
    fn node(&self) -> NodeRef<'g> {
        self.0
    }
}

impl<'g> IfElseStmt<'g> {
    pub fn kw_if_token(&self) -> Option<TokenRef<'g>> {
        self.0.child_token(0, 23) // KW_IF
    }
    pub fn lparen_token(&self) -> Option<TokenRef<'g>> {
        self.0.child_token(1, 7) // LPAREN
    }
    pub fn expr(&self) -> Option<Expr<'g>> {
        Expr::cast(self.0.child_node(2)?)
    }
    pub fn rparen_token(&self) -> Option<TokenRef<'g>> {
        self.0.child_token(3, 8) // RPAREN
    }
    pub fn block(&self) -> Option<Block<'g>> {
        Block::cast(self.0.child_node(4)?)
    }
    pub fn kw_else_token(&self) -> Option<TokenRef<'g>> {
        self.0.child_token(5, 24) // KW_ELSE
    }
    pub fn block_2(&self) -> Option<Block<'g>> {
        Block::cast(self.0.child_node(6)?)
    }
}

/// `block → LBRACE stmts RBRACE`
#[derive(Clone, Copy, Debug)]
pub struct Block<'g>(pub NodeRef<'g>);

impl<'g> AstNode<'g> for Block<'g> {
    fn cast(node: NodeRef<'g>) -> Option<Self> {
        (node.nt() == 3 && node.prod() == 8).then(|| Block(node))
    }
    fn node(&self) -> NodeRef<'g> {
        self.0
    }
}

impl<'g> Block<'g> {
    pub fn lbrace_token(&self) -> Option<TokenRef<'g>> {
        self.0.child_token(0, 11) // LBRACE
    }
    pub fn stmts(&self) -> Option<Stmts<'g>> {
        Stmts::cast(self.0.child_node(1)?)
    }
    pub fn rbrace_token(&self) -> Option<TokenRef<'g>> {
        self.0.child_token(2, 12) // RBRACE
    }
}

/// `expr` — 10 productions.
#[derive(Clone, Copy, Debug)]
pub enum Expr<'g> {
    AddExpr(AddExpr<'g>),
    SubExpr(SubExpr<'g>),
    MulExpr(MulExpr<'g>),
    DivExpr(DivExpr<'g>),
    NumLit(NumLit<'g>),
    StrLit(StrLit<'g>),
    NameRef(NameRef<'g>),
    CallExpr(CallExpr<'g>),
    ParenExpr(ParenExpr<'g>),
    ListExpr(ListExpr<'g>),
}

impl<'g> AstNode<'g> for Expr<'g> {
    fn cast(node: NodeRef<'g>) -> Option<Self> {
        if node.nt() != 4 {
            return None;
        }
        match node.prod() {
            9 => Some(Expr::AddExpr(AddExpr(node))),
            10 => Some(Expr::SubExpr(SubExpr(node))),
            11 => Some(Expr::MulExpr(MulExpr(node))),
            12 => Some(Expr::DivExpr(DivExpr(node))),
            13 => Some(Expr::NumLit(NumLit(node))),
            14 => Some(Expr::StrLit(StrLit(node))),
            15 => Some(Expr::NameRef(NameRef(node))),
            16 => Some(Expr::CallExpr(CallExpr(node))),
            17 => Some(Expr::ParenExpr(ParenExpr(node))),
            18 => Some(Expr::ListExpr(ListExpr(node))),
            _ => None,
        }
    }
    fn node(&self) -> NodeRef<'g> {
        match self {
            Expr::AddExpr(x) => x.0,
            Expr::SubExpr(x) => x.0,
            Expr::MulExpr(x) => x.0,
            Expr::DivExpr(x) => x.0,
            Expr::NumLit(x) => x.0,
            Expr::StrLit(x) => x.0,
            Expr::NameRef(x) => x.0,
            Expr::CallExpr(x) => x.0,
            Expr::ParenExpr(x) => x.0,
            Expr::ListExpr(x) => x.0,
        }
    }
}

/// `expr → expr PLUS expr`
#[derive(Clone, Copy, Debug)]
pub struct AddExpr<'g>(pub NodeRef<'g>);

impl<'g> AstNode<'g> for AddExpr<'g> {
    fn cast(node: NodeRef<'g>) -> Option<Self> {
        (node.nt() == 4 && node.prod() == 9).then(|| AddExpr(node))
    }
    fn node(&self) -> NodeRef<'g> {
        self.0
    }
}

impl<'g> AddExpr<'g> {
    pub fn expr(&self) -> Option<Expr<'g>> {
        Expr::cast(self.0.child_node(0)?)
    }
    pub fn plus_token(&self) -> Option<TokenRef<'g>> {
        self.0.child_token(1, 13) // PLUS
    }
    pub fn expr_2(&self) -> Option<Expr<'g>> {
        Expr::cast(self.0.child_node(2)?)
    }
}

/// `expr → expr MINUS expr`
#[derive(Clone, Copy, Debug)]
pub struct SubExpr<'g>(pub NodeRef<'g>);

impl<'g> AstNode<'g> for SubExpr<'g> {
    fn cast(node: NodeRef<'g>) -> Option<Self> {
        (node.nt() == 4 && node.prod() == 10).then(|| SubExpr(node))
    }
    fn node(&self) -> NodeRef<'g> {
        self.0
    }
}

impl<'g> SubExpr<'g> {
    pub fn expr(&self) -> Option<Expr<'g>> {
        Expr::cast(self.0.child_node(0)?)
    }
    pub fn minus_token(&self) -> Option<TokenRef<'g>> {
        self.0.child_token(1, 14) // MINUS
    }
    pub fn expr_2(&self) -> Option<Expr<'g>> {
        Expr::cast(self.0.child_node(2)?)
    }
}

/// `expr → expr STAR expr`
#[derive(Clone, Copy, Debug)]
pub struct MulExpr<'g>(pub NodeRef<'g>);

impl<'g> AstNode<'g> for MulExpr<'g> {
    fn cast(node: NodeRef<'g>) -> Option<Self> {
        (node.nt() == 4 && node.prod() == 11).then(|| MulExpr(node))
    }
    fn node(&self) -> NodeRef<'g> {
        self.0
    }
}

impl<'g> MulExpr<'g> {
    pub fn expr(&self) -> Option<Expr<'g>> {
        Expr::cast(self.0.child_node(0)?)
    }
    pub fn star_token(&self) -> Option<TokenRef<'g>> {
        self.0.child_token(1, 15) // STAR
    }
    pub fn expr_2(&self) -> Option<Expr<'g>> {
        Expr::cast(self.0.child_node(2)?)
    }
}

/// `expr → expr SLASH expr`
#[derive(Clone, Copy, Debug)]
pub struct DivExpr<'g>(pub NodeRef<'g>);

impl<'g> AstNode<'g> for DivExpr<'g> {
    fn cast(node: NodeRef<'g>) -> Option<Self> {
        (node.nt() == 4 && node.prod() == 12).then(|| DivExpr(node))
    }
    fn node(&self) -> NodeRef<'g> {
        self.0
    }
}

impl<'g> DivExpr<'g> {
    pub fn expr(&self) -> Option<Expr<'g>> {
        Expr::cast(self.0.child_node(0)?)
    }
    pub fn slash_token(&self) -> Option<TokenRef<'g>> {
        self.0.child_token(1, 16) // SLASH
    }
    pub fn expr_2(&self) -> Option<Expr<'g>> {
        Expr::cast(self.0.child_node(2)?)
    }
}

/// `expr → NUMBER`
#[derive(Clone, Copy, Debug)]
pub struct NumLit<'g>(pub NodeRef<'g>);

impl<'g> AstNode<'g> for NumLit<'g> {
    fn cast(node: NodeRef<'g>) -> Option<Self> {
        (node.nt() == 4 && node.prod() == 13).then(|| NumLit(node))
    }
    fn node(&self) -> NodeRef<'g> {
        self.0
    }
}

impl<'g> NumLit<'g> {
    pub fn number_token(&self) -> Option<TokenRef<'g>> {
        self.0.child_token(0, 5) // NUMBER
    }
}

/// `expr → STRING`
#[derive(Clone, Copy, Debug)]
pub struct StrLit<'g>(pub NodeRef<'g>);

impl<'g> AstNode<'g> for StrLit<'g> {
    fn cast(node: NodeRef<'g>) -> Option<Self> {
        (node.nt() == 4 && node.prod() == 14).then(|| StrLit(node))
    }
    fn node(&self) -> NodeRef<'g> {
        self.0
    }
}

impl<'g> StrLit<'g> {
    pub fn string_token(&self) -> Option<TokenRef<'g>> {
        self.0.child_token(0, 3) // STRING
    }
}

/// `expr → IDENT`
#[derive(Clone, Copy, Debug)]
pub struct NameRef<'g>(pub NodeRef<'g>);

impl<'g> AstNode<'g> for NameRef<'g> {
    fn cast(node: NodeRef<'g>) -> Option<Self> {
        (node.nt() == 4 && node.prod() == 15).then(|| NameRef(node))
    }
    fn node(&self) -> NodeRef<'g> {
        self.0
    }
}

impl<'g> NameRef<'g> {
    pub fn ident_token(&self) -> Option<TokenRef<'g>> {
        self.0.child_token(0, 6) // IDENT
    }
}

/// `expr → IDENT LPAREN args RPAREN`
#[derive(Clone, Copy, Debug)]
pub struct CallExpr<'g>(pub NodeRef<'g>);

impl<'g> AstNode<'g> for CallExpr<'g> {
    fn cast(node: NodeRef<'g>) -> Option<Self> {
        (node.nt() == 4 && node.prod() == 16).then(|| CallExpr(node))
    }
    fn node(&self) -> NodeRef<'g> {
        self.0
    }
}

impl<'g> CallExpr<'g> {
    pub fn ident_token(&self) -> Option<TokenRef<'g>> {
        self.0.child_token(0, 6) // IDENT
    }
    pub fn lparen_token(&self) -> Option<TokenRef<'g>> {
        self.0.child_token(1, 7) // LPAREN
    }
    pub fn args(&self) -> Option<Args<'g>> {
        Args::cast(self.0.child_node(2)?)
    }
    pub fn rparen_token(&self) -> Option<TokenRef<'g>> {
        self.0.child_token(3, 8) // RPAREN
    }
}

/// `expr → LPAREN expr RPAREN`
#[derive(Clone, Copy, Debug)]
pub struct ParenExpr<'g>(pub NodeRef<'g>);

impl<'g> AstNode<'g> for ParenExpr<'g> {
    fn cast(node: NodeRef<'g>) -> Option<Self> {
        (node.nt() == 4 && node.prod() == 17).then(|| ParenExpr(node))
    }
    fn node(&self) -> NodeRef<'g> {
        self.0
    }
}

impl<'g> ParenExpr<'g> {
    pub fn lparen_token(&self) -> Option<TokenRef<'g>> {
        self.0.child_token(0, 7) // LPAREN
    }
    pub fn expr(&self) -> Option<Expr<'g>> {
        Expr::cast(self.0.child_node(1)?)
    }
    pub fn rparen_token(&self) -> Option<TokenRef<'g>> {
        self.0.child_token(2, 8) // RPAREN
    }
}

/// `expr → LBRACKET args RBRACKET`
#[derive(Clone, Copy, Debug)]
pub struct ListExpr<'g>(pub NodeRef<'g>);

impl<'g> AstNode<'g> for ListExpr<'g> {
    fn cast(node: NodeRef<'g>) -> Option<Self> {
        (node.nt() == 4 && node.prod() == 18).then(|| ListExpr(node))
    }
    fn node(&self) -> NodeRef<'g> {
        self.0
    }
}

impl<'g> ListExpr<'g> {
    pub fn lbracket_token(&self) -> Option<TokenRef<'g>> {
        self.0.child_token(0, 9) // LBRACKET
    }
    pub fn args(&self) -> Option<Args<'g>> {
        Args::cast(self.0.child_node(1)?)
    }
    pub fn rbracket_token(&self) -> Option<TokenRef<'g>> {
        self.0.child_token(2, 10) // RBRACKET
    }
}

/// `args` — 2 productions.
#[derive(Clone, Copy, Debug)]
pub enum Args<'g> {
    ArgsEmpty(ArgsEmpty<'g>),
    ArgsSome(ArgsSome<'g>),
}

impl<'g> AstNode<'g> for Args<'g> {
    fn cast(node: NodeRef<'g>) -> Option<Self> {
        if node.nt() != 5 {
            return None;
        }
        match node.prod() {
            19 => Some(Args::ArgsEmpty(ArgsEmpty(node))),
            20 => Some(Args::ArgsSome(ArgsSome(node))),
            _ => None,
        }
    }
    fn node(&self) -> NodeRef<'g> {
        match self {
            Args::ArgsEmpty(x) => x.0,
            Args::ArgsSome(x) => x.0,
        }
    }
}

/// `args → ε`
#[derive(Clone, Copy, Debug)]
pub struct ArgsEmpty<'g>(pub NodeRef<'g>);

impl<'g> AstNode<'g> for ArgsEmpty<'g> {
    fn cast(node: NodeRef<'g>) -> Option<Self> {
        (node.nt() == 5 && node.prod() == 19).then(|| ArgsEmpty(node))
    }
    fn node(&self) -> NodeRef<'g> {
        self.0
    }
}

/// `args → args_ne`
#[derive(Clone, Copy, Debug)]
pub struct ArgsSome<'g>(pub NodeRef<'g>);

impl<'g> AstNode<'g> for ArgsSome<'g> {
    fn cast(node: NodeRef<'g>) -> Option<Self> {
        (node.nt() == 5 && node.prod() == 20).then(|| ArgsSome(node))
    }
    fn node(&self) -> NodeRef<'g> {
        self.0
    }
}

impl<'g> ArgsSome<'g> {
    pub fn args_ne(&self) -> Option<ArgsNe<'g>> {
        ArgsNe::cast(self.0.child_node(0)?)
    }
}

/// `args_ne` — balanced list of `Expr` (envelope L4).
#[derive(Clone, Copy, Debug)]
pub struct ArgsNe<'g>(pub NodeRef<'g>);

impl<'g> AstNode<'g> for ArgsNe<'g> {
    fn cast(node: NodeRef<'g>) -> Option<Self> {
        (node.nt() == 6 && node.prod() == crate::green::LIST_PROD).then(|| ArgsNe(node))
    }
    fn node(&self) -> NodeRef<'g> {
        self.0
    }
}

impl<'g> ArgsNe<'g> {
    pub fn items(&self) -> Vec<Expr<'g>> {
        self.0
            .flat_symbol_children()
            .into_iter()
            .filter_map(|c| match c {
                crate::typed::SymbolChild::Node(n) => Expr::cast(n),
                _ => None,
            })
            .collect()
    }
}
